### ISSUE TITLE
malformed pattern (missing '] AGAIN!....

### ISSUE THREAD

**Issue by NimaGame** [amirhmz/XamarinTG#2]
Again this problem:
*** 1455974613.025859 lua: .///bot/utils.lua:489: malformed pattern (missing ']') [08:23] 🎄NıмαGαмε🎄 >>> !creategroup TEST *** 1455974619.418231 lua: .///bot/utils.lua:489: malformed pattern (missing ']') [08:23] 🎄NıмαGαмε🎄 >>> !id

**Comment by amirhmz** [comment]
Source investigated and no problem.
Please re- check the clone source and the installation process carefully as education go ahead.
